language: erlang
env: MIX_ENV=test
otp_release:
  - 17.0
before_install:
  - wget http://s3.hex.pm/builds/elixir/v1.0.0.zip
  - unzip -d elixir v1.0.0.zip
before_script:
  - export PATH=`pwd`/elixir/bin:$PATH
  - mix archive.install http://s3.hex.pm/installs/hex.ez --force
  - mix deps.get
script:
  - mix test --include integration
notifications:
