defmodule Hexoku.API.Account do
	alias Hexoku.Request
	@moduledoc """
	An account represents an individual signed up to use the Heroku platform.

	## Attributes
	<dl>
		<dt>id</dt> <dd>unique identifier of item generated by Heroku</dd>
		<dt>name</dt> <dd>full name of the account owner</dd>
		<dt>allow_tracking</dt> <dd>whether to allow third party web activity tracking. default: true</dd>
		<dt>beta</dt> <dd>whether allowed to utilize beta Heroku features</dd>
		<dt>email</dt> <dd>unique email address of account</dd>
		<dt>verified</dt> <dd>whether account has been verified with billing information</dd>
		<dt>two_factor_authentication</dt> <dd>whether two-factor auth is enabled on the account</dd>
		<dt>last_login</dt> <dd>when account last authorized with Heroku</dd>
		<dt>created_at</dt> <dd>when account was created</dd>
		<dt>updated_at</dt> <dd>when account was updated</dd>
	</dl>

	For more info read the [Heroku API Reference](https://devcenter.heroku.com/articles/platform-api-reference#account)
	"""

	@doc """
	Info for account.

	## Examples
		client |> Hexoku.API.info()
	"""
	@spec info(Hexoku.Client.t) :: Map.t
	def info(client), do: Request.get(client, "/account")

	@doc """
	Update account.

	## Examples
		client |> Hexoku.API.update(%{name: "Nonni DeMaze"})
	"""
	@spec update(Hexoku.Client.t, Map.t) :: Map.t
	def update(client, body), do: Request.get(client, "/account", body)

end
