defmodule Hexoku.API.Domains do
	alias Hexoku.Request
	@moduledoc """
	Domains define what web routes should be routed to an app on Heroku.

	## Attributes
	<dl>
		<dt>id</dt> <dd>unique identifier of item generated by Heroku</dd>
		<dt>hostname</dt> <dd>full hostname</dd>
		<dt>created_at</dt> <dd>when item was created</dd>
		<dt>updated_at</dt> <dd>when item was last modified</dd>
	</dl>

	For more info read the [Heroku API Reference](https://devcenter.heroku.com/articles/platform-api-reference#domain)
	"""

	@doc """
	List existing domains.

	## Examples
		client |> Hexoku.API.Domains.list("myapp")
	"""
	@spec list(Hexoku.Client.t, binary) :: [Map.t]
	def list(client, app), do: Request.get(client, "/apps/#{app}/domains")

	@doc """
	Info for existing domain.

	## Examples
		client |> Hexoku.API.Domains.info("myapp", "myapp.example.com")
	"""
	@spec info(Hexoku.Client.t, binary, binary) :: Map.t
	def info(client, app, domain), do: Request.get(client, "/apps/#{app}/domains/#{domain}")

	@doc """
	Create a new domain.

	## Examples
		client |> Hexoku.API.Domains.create("myapp", "myapp.example.com")
	"""
	@spec create(Hexoku.Client.t, binary, binary) :: Map.t
	def create(client, app, domain), do: Request.post(client, "/apps/#{app}/domains", %{domain: domain})

	@doc """
	Delete an existing domain

	## Examples
		client |> Hexoku.API.Domains.delete("myapp", "myapp.example.com")
	"""
	@spec delete(Hexoku.Client.t, binary, binary) :: Map.t
	def delete(client, app, domain), do: Request.delete(client, "/apps/#{app}/domains/#{domain}")

end
