defmodule Hexoku.API.Organizations do
	alias Hexoku.Request
	@moduledoc """
	Organizations allow you to manage access to a shared group of applications across your development team.

	## Attributes
	<dl>
		<dt>id</dt> <dd>unique identifier of item generated by Heroku</dd>
		<dt>name</dt> <dd>unique name of item provided by the user</dd>
		<dt>credit_card_collections</dt> <dd>whether charges incurred by the org are paid by credit card.</dd>
		<dt>default</dt> <dd>whether to use this organization when none is specified</dd>
		<dt>provisioned_licenses</dt> <dd>whether the org is provisioned licenses by salesforce.</dd>
		<dt>role</dt> <dd>your role in the organization ["admin", "member", "collaborator"]</dd>
		<dt>created_at</dt> <dd>when item was created</dd>
		<dt>updated_at</dt> <dd>when item was last modified</dd>
	</dl>

	For more info read the [Heroku API Reference](https://devcenter.heroku.com/articles/platform-api-reference#organization)
	"""

	@doc """
	List organizations in which you are a member.

	## Examples
		client |> Hexoku.API.Organizations.list()
	"""
	@spec list(Hexoku.Client.t) :: [Map.t]
	def list(client), do: Request.get(client, "/organizations")

	@doc """
	Info for an organization.

	## Examples
		client |> Hexoku.API.Organizations.info("cedar")
	"""
	@spec update(Hexoku.Client.t, binary, Map.t) :: Map.t
	def update(client, org, body), do: Request.patch(client, "/organizations/#{org}", body)


end
