defmodule Hexoku.API.Regions do
	alias Hexoku.Request
	@moduledoc """
	A region represents a geographic location in which your application may run.

	## Attributes
	<dl>
		<dt>id</dt> <dd>unique identifier of item generated by Heroku</dd>
		<dt>name</dt> <dd>name of region</dd>
		<dt>description</dt> <dd>description of region</dd>
		<dt>created_at</dt> <dd>when item was created</dd>
		<dt>updated_at</dt> <dd>when item was last modified</dd>
	</dl>

	For more info read the [Heroku API Reference](https://devcenter.heroku.com/articles/platform-api-reference#region)
	"""

	@doc """
	List available regions.

	## Examples
		client |> Hexoku.API.Regions.list()
	"""
	@spec list(Hexoku.Client.t) :: [Map.t]
	def list(client), do: Request.get(client, "/regions")

	@doc """
	Info for existing region.

	## Examples
		client |> Hexoku.API.Regions.info("us")
	"""
	@spec info(Hexoku.Client.t, binary) :: Map.t
	def info(client, region), do: Request.get(client, "/regions/#{region}")

end
