defmodule Hexoku.API.Stacks do
	alias Hexoku.Request
	@moduledoc """
	Stacks are the different application execution environments available in the Heroku platform.

	## Attributes
	<dl>
		<dt>id</dt> <dd>unique identifier of item generated by Heroku</dd>
		<dt>name</dt> <dd>unique name of item provided by the user</dd>
		<dt>state</dt> <dd>availability of this stack: beta, deprecated or public</dd>
		<dt>created_at</dt> <dd>when item was created</dd>
		<dt>updated_at</dt> <dd>when item was last modified</dd>
	</dl>

	For more info read the [Heroku API Reference](https://devcenter.heroku.com/articles/platform-api-reference#stack)
	"""

	@doc """
	List available stacks.

	## Examples
		client |> Hexoku.API.Stacks.list
	"""
	@spec list(Hexoku.Client.t) :: [Map.t]
	def list(client), do: Request.get(client, "/stacks")

	@doc """
	Get info on a specific Stack.

	## Examples
		client |> Hexoku.API.Stacks.info("cedar")
	"""
	@spec info(Hexoku.Client.t, binary) :: Map.t
	def info(client, stack), do: Request.get(client, "/stacks/#{stack}")

end
